# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go WASM - Build, Test & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.22.5'
  CHROME_VERSION: '129'
  FIREFOX_VERSION: '131.0.3'
  CHROME_DRIVER_VERSION: '129.0.6668.100'
  GECKO_DRIVER_VERSION: '0.35.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # It would be easier to see if there any other failing tests in another OS. Leaving it to true, if one workflow fails, the rest will be cancelled
      fail-fast: false # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      shell: bash
      run: ./build_wasm

    - name: Get WebDrivers
      uses: actions/checkout@v4
      with:
        repository: 'padaiyal/depot'
        path: ./depot
        sparse-checkout: 'webdriver' # Only pull under webdriver directory
        sparse-checkout-cone-mode: false

    - name: Set up Chrome Browser
      id: setup-chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ env.CHROME_VERSION }}

    - name: Set up Firefox Browser
      id: setup-firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ env.FIREFOX_VERSION }}

    - name: Set Browsers Env
      shell: bash
      run: |
        CHROME_BROWSER_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
        echo "CHROME_BROWSER_PATH=${CHROME_BROWSER_PATH}" >> $GITHUB_ENV
        
        FIREFOX_BROWSER_PATH="${{ steps.setup-firefox.outputs.firefox-path }}"
        if [[ ${{ matrix.os }} == "windows-latest" ]]; then
          FIREFOX_BROWSER_PATH="${FIREFOX_BROWSER_PATH}.exe"
        fi
        echo "FIREFOX_BROWSER_PATH=${FIREFOX_BROWSER_PATH}" >> $GITHUB_ENV

    - name: Test - End to End Tests
      shell: bash
      run: |
        ./run_tests

    - name: Commit and push WASM static pages
      if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      env:
        CI_COMMIT_MESSAGE: Add WASM static pages - $(date +'%Y-%m-%dT%H:%M:%S')
        CI_COMMIT_AUTHOR: padaiyal
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add --force script/*.wasm
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push